development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: chronussurvey_development
  pool: 5
  username: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: chronussurvey_test
  pool: 5
  username: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: chronussurvey_production
  pool: 5
  username: root