development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: chronussvrvey_development
  pool: 5
  username: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: chronussvrvey_test
  pool: 5
  username: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: chronussvrvey_production
  pool: 5
  username: root